### PR TITLE
chore: change sdk transfer examples to not use goerli

### PR DESCRIPTION
**Pull request by tcar121293**
fix sdk transfer examples
## Description
remove and replace goerli from examples
evm -> evm (fungible): Mumbai -> sepolia
evm -> evm(generic): sepolia -> mumbai
evm -> substrate: sepolia -> rhala (resourceID: 0x0000000000000000000000000000000000000000000000000000000000001100)
substrate-> evm: rhala -> sepolia (resourceID: 0x0000000000000000000000000000000000000000000000000000000000001100)
## Related Issue Or Context

Closes: #355 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

### CODE REVIEW

**Comment by LyonSsS** [comment]
Tested using the SDK_examples from this branch: 
1. EVM - EVM example PASSED 
image
2. EVM - EVM example Failed due to set-up **const DESTINATION_CHAIN_ID = 7; // Mumbai** this should have been ID: 80001
3. EVM - Substrate example PASSED
image
4. Substrate - EVM Failed du to set-up " RESOURCE_ID,
    "5000000000000" // 12 decimal places" this should be set to 6 decimals for resource ID 0x0000000000000000000000000000000000000000000000000000000000001100

**Review by MakMuftic — DISMISSED** [review]

**Comment by LyonSsS** [comment]
Retested and now everything is fine 
image
One last thing to update is the substrate RPC from "wss://subbridge-test.phala.network/rhala/ws" to "wss://rhala-node.phala.network/ws"

**Review by MakMuftic — DISMISSED** [review]

**Review by LyonSsS — APPROVED** [review]
Verified code changes and tested on testnet. This is not validated by QA

**Comment by haochizzle** [comment]
i pulled this latest pr to try out the evm-to-evm-fungible-transfer example and it kept failing. 

the notable error messages i was receiving was:

```bash
➜  evm-to-evm-fungible-transfer git:(tcar/fix-examples) yarn run transfer
/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/transfer.ts:27:12 - error TS2352: Conversion of type 'TransferStatusResponse[]' to type '{ status: string; explorerUrl: string; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'TransferStatusResponse[]' is missing the following properties from type '{ status: string; explorerUrl: string; }': status, explorerUrl

27     return data as { status: string; explorerUrl: string };
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/timho/Sygma_DevRel/github/sygma-sdk/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2352 ]
```

and something about gasLimits. i got it to work after a bit of tinkering + manually specifying the gas limit. i wonder if this is just my machine or can it be reproduced by other ppl?

**Comment by haochizzle** [comment]
could we also update the example READMEs to include instructions for adding `<NETWORK>_RPC_URL="xxx"` since there's now code calling e.g. process.env.MUMBAI_RPC_URL? @tcar121293 @MakMuftic

**Comment by LyonSsS** [comment]
Retested and fixed the type issue. 
Also the logs are improved to display e2e flow 
image
Please retry with this latest branch @haochizzle

**Review by LyonSsS — APPROVED** [review]
Local branch passed with success, only by manipulating RPC provider. 
QA review: Pass

**Comment by tcar121293** [comment]
> could we also update the example READMEs to include instructions for adding `<NETWORK>_RPC_URL="xxx"` since there's now code calling e.g. process.env.MUMBAI_RPC_URL? @tcar121293 @MakMuftic

I updated the readme with new optional env vars

**Review by wainola — APPROVED** [review]

**Review by MakMuftic — APPROVED** [review]

**Pull request merged**
