### PR TITLE
fix: Check/update dependencies for packages

### PR DESCRIPTION
**Pull request by enemycnt**
## Related Issue Or Context

Closes: #123 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

### CODE REVIEW

**Comment by BeroBurny** [comment]
Can be #130 included in this PR?

**Review by BeroBurny — CHANGES_REQUESTED** [review]
Please use `yarn outdated` to check available package updates.
Found a lot of packages that have patches and did not updated in this PR

**Comment by enemycnt** [comment]
> Can be #130 included in this PR?

I've created separate [PR](https://github.com/sygmaprotocol/sygma-sdk/pull/139) for that issue

**Review by wainola — APPROVED** [review]

**Comment by wainola** [comment]
Can we merge this?

**Pull request merged**
